:zap: upgrade starter to Angular 8. Closes #26
vaadin/base-starter-angular pull request #27
Opened 2019-07-24 07:32 UTC by peterblazejewicz

- dependencies upgraded manuallyto version 8
- starter project structure changed to reflect current project
  structures generated with @angular/cli
- migrate to new features from NG 8 with lazy loading, differential
  loading
- minor changes in README
- fix failing unit tests
- fix e2e tests

Thanks!

2019-08-05 11:20 UTC, tomivirkki requested changes
Thanks for the PR. Works fine on other browsers but the app won't start up on IE11 however.

2019-08-09 19:57 UTC, peterblazejewicz commented
I think I forgot to enable the IE support (which is off by default in NG 8). I do not have the PC at the hand atm, will try to investigate the update asap.
Thanks!

2019-09-04 07:19 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vaadin/base-starter-angular?pullRequest=27) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/vaadin/base-starter-angular?pullRequest=27) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: alvarezguille<br/>:x: peterblazejewicz<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vaadin/base-starter-angular?pullRequest=27) it.</sub>

2019-09-04 07:43 UTC, alvarezguille commented
Thanks for the contribution, unfortunately we archived the repo as we are not actively maintaining this starter project.
We tried to merge this PR with ng 8 without IE config to a separate branch in case it's useful for someone who happens to find it, but we can't do it without signed CLA

2019-09-04 07:43 UTC, closed without merging